import Head from "next/head";
import axiosConfig from "../config/axiosConfig";
import List from "../components/list";
import { useState, useEffect } from "react";

export default function Home() {
  const [posts, setPosts] = useState(null);

  useEffect(() => {
    axiosConfig
      .get("/post")
      .then((res) => setPosts(res.data.data))
      .catch((err) => console.error(err));
  }, []);

  return (
    <>
      <Head>
        <title>Social Media Routing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <List data={posts} origin="post" />
    </>
  );
}
